# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190421_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='北京王府井', max_length=255, verbose_name='用户地址'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
