# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-24 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20190422_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recv_name', models.CharField(max_length=100, verbose_name='收货人')),
                ('recv_tel', models.CharField(max_length=20, verbose_name='收货电话')),
                ('province', models.CharField(max_length=100, verbose_name='收货人省份')),
                ('city', models.CharField(max_length=100, verbose_name='收货城市')),
                ('area', models.CharField(max_length=255, verbose_name='收货人县区')),
                ('street', models.CharField(max_length=255, verbose_name='收货人街道')),
                ('status', models.BooleanField(default=False, verbose_name='是否是默认地址')),
                ('desc', models.CharField(max_length=255, verbose_name='详细地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='地址所属用户')),
            ],
        ),
    ]
